# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'

target 'little-todo-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for little-todo-ios

  pod 'FontAwesomeKit/FontAwesome'
  pod 'Toast', '~> 4.0.0'

end
